CREATE DATABASE IF NOT EXISTS photos_db;

USE photos_db;

CREATE TABLE photos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	image_base64 MEDIUMTEXT NOT NULL,
	photo_name TEXT NOT NULL,
	photo_path TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
